import { createElement } from "lwc";
import ReviewCard from "c/reviewCard";

describe("c-review-card", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-review-card", {
      is: ReviewCard
    });
    element.reviewData = {
      Valoracion__c: 4,
      Comentario__c: "Muy bien",
      CreatedDate: "2023-07-07 00:33:57"
    };
    // Act
    document.body.appendChild(element);

    // Assert
    const comentario = element.shadowRoot.querySelector(
      ".slds-m-vertical_small"
    );
    expect(comentario.textContent).toBe("Muy bien");
    const createdDate = element.shadowRoot.querySelector(
      ".slds-text-color_weak"
    );
    expect(createdDate.textContent).toBe("7 de julio de 2023");
  });
});
