import { createElement } from "lwc";
import StarsRating from "c/starsRating";

describe("c-stars-rating", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-stars-rating", {
      is: StarsRating
    });
    element.ratingData = 4;

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    const iconsArray = element.shadowRoot.querySelectorAll("lightning-icon");
    expect(iconsArray[0].variant).toBe("warning");
    expect(iconsArray[1].variant).toBe("warning");
    expect(iconsArray[2].variant).toBe("warning");
    expect(iconsArray[3].variant).toBe("warning");
    expect(iconsArray[4].variant).toBe("default");
    expect(iconsArray.length).toBe(5);
  });
});
